version: '3'

services:
  main-service:
    build: ./
    volumes:
     - ./:/app
    ports:
     - 8080:8080
  web-service:
    image: php:apache
    volumes:
     - ./web:/var/www/html
    ports:
     - 8081:80
    depends_on:
     - main-service
